// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: inference.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateEventType int32

const (
	GenerateEventType_EVENT_UNSPECIFIED GenerateEventType = 0
	GenerateEventType_EVENT_TOKEN       GenerateEventType = 1
	GenerateEventType_EVENT_TOOL_USE    GenerateEventType = 2
	GenerateEventType_EVENT_FINAL       GenerateEventType = 3
)

// Enum value maps for GenerateEventType.
var (
	GenerateEventType_name = map[int32]string{
		0: "EVENT_UNSPECIFIED",
		1: "EVENT_TOKEN",
		2: "EVENT_TOOL_USE",
		3: "EVENT_FINAL",
	}
	GenerateEventType_value = map[string]int32{
		"EVENT_UNSPECIFIED": 0,
		"EVENT_TOKEN":       1,
		"EVENT_TOOL_USE":    2,
		"EVENT_FINAL":       3,
	}
)

func (x GenerateEventType) Enum() *GenerateEventType {
	p := new(GenerateEventType)
	*p = x
	return p
}

func (x GenerateEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GenerateEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_proto_enumTypes[0].Descriptor()
}

func (GenerateEventType) Type() protoreflect.EnumType {
	return &file_inference_proto_enumTypes[0]
}

func (x GenerateEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GenerateEventType.Descriptor instead.
func (GenerateEventType) EnumDescriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

type StopReason int32

const (
	StopReason_STOP_UNSPECIFIED StopReason = 0
	StopReason_STOP_END_TURN    StopReason = 1 // Model tự kết thúc lượt
	StopReason_STOP_MAX_TOKENS  StopReason = 2 // Đạt giới hạn max_tokens
	StopReason_STOP_TOOL_USE    StopReason = 3 // Model muốn gọi tool
	StopReason_STOP_CANCELLED   StopReason = 4 // Bị cancel từ client
	StopReason_STOP_ERROR       StopReason = 5 // Lỗi inference
)

// Enum value maps for StopReason.
var (
	StopReason_name = map[int32]string{
		0: "STOP_UNSPECIFIED",
		1: "STOP_END_TURN",
		2: "STOP_MAX_TOKENS",
		3: "STOP_TOOL_USE",
		4: "STOP_CANCELLED",
		5: "STOP_ERROR",
	}
	StopReason_value = map[string]int32{
		"STOP_UNSPECIFIED": 0,
		"STOP_END_TURN":    1,
		"STOP_MAX_TOKENS":  2,
		"STOP_TOOL_USE":    3,
		"STOP_CANCELLED":   4,
		"STOP_ERROR":       5,
	}
)

func (x StopReason) Enum() *StopReason {
	p := new(StopReason)
	*p = x
	return p
}

func (x StopReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StopReason) Descriptor() protoreflect.EnumDescriptor {
	return file_inference_proto_enumTypes[1].Descriptor()
}

func (StopReason) Type() protoreflect.EnumType {
	return &file_inference_proto_enumTypes[1]
}

func (x StopReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StopReason.Descriptor instead.
func (StopReason) EnumDescriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

// GenerateRequest — gửi từ Go xuống Python worker.
type GenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique request ID for tracing/cancellation.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Session ID để Python log / debug (không dùng cho context management).
	SessionId string `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Messages đã được Go format sẵn theo internal canonical format.
	// Python chỉ cần tokenize và chạy inference, không cần biết protocol gốc.
	Messages []*Message `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	// Optional system prompt.
	SystemPrompt string `protobuf:"bytes,4,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	// Sampling parameters.
	SamplingParams *SamplingParams `protobuf:"bytes,5,opt,name=sampling_params,json=samplingParams,proto3" json:"sampling_params,omitempty"`
	// Tool definitions available for this request (JSON schema format).
	Tools         []*ToolDefinition `protobuf:"bytes,6,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *GenerateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *GenerateRequest) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GenerateRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *GenerateRequest) GetSamplingParams() *SamplingParams {
	if x != nil {
		return x.SamplingParams
	}
	return nil
}

func (x *GenerateRequest) GetTools() []*ToolDefinition {
	if x != nil {
		return x.Tools
	}
	return nil
}

// Message — internal canonical format, Go đã convert từ Anthropic/OpenAI.
type Message struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Role    string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`       // "user" | "assistant" | "system"
	Content string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"` // plain text content (tool results được inline vào đây)
	// Tool calls made by the assistant in this message (cho multi-turn history).
	ToolCalls []*ToolCall `protobuf:"bytes,3,rep,name=tool_calls,json=toolCalls,proto3" json:"tool_calls,omitempty"`
	// If this is a tool result message.
	ToolCallId    string `protobuf:"bytes,4,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolResult    string `protobuf:"bytes,5,opt,name=tool_result,json=toolResult,proto3" json:"tool_result,omitempty"`
	IsError       bool   `protobuf:"varint,6,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetToolCalls() []*ToolCall {
	if x != nil {
		return x.ToolCalls
	}
	return nil
}

func (x *Message) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *Message) GetToolResult() string {
	if x != nil {
		return x.ToolResult
	}
	return ""
}

func (x *Message) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// ToolCall — một tool call từ assistant.
type ToolCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCall) Reset() {
	*x = ToolCall{}
	mi := &file_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCall) ProtoMessage() {}

func (x *ToolCall) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCall.ProtoReflect.Descriptor instead.
func (*ToolCall) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{2}
}

func (x *ToolCall) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCall) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCall) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// ToolDefinition — định nghĩa một tool có sẵn.
type ToolDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Parameters    string                 `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"` // JSON Schema string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolDefinition) Reset() {
	*x = ToolDefinition{}
	mi := &file_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolDefinition) ProtoMessage() {}

func (x *ToolDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolDefinition.ProtoReflect.Descriptor instead.
func (*ToolDefinition) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{3}
}

func (x *ToolDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolDefinition) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolDefinition) GetParameters() string {
	if x != nil {
		return x.Parameters
	}
	return ""
}

// SamplingParams — tham số điều khiển quá trình sinh token.
type SamplingParams struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MaxTokens     int32                  `protobuf:"varint,1,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"` // default: 1024
	Temperature   float32                `protobuf:"fixed32,2,opt,name=temperature,proto3" json:"temperature,omitempty"`             // default: 0.7
	TopP          float32                `protobuf:"fixed32,3,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`               // default: 0.9
	TopK          int32                  `protobuf:"varint,4,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`                // default: 50
	StopSequences []string               `protobuf:"bytes,5,rep,name=stop_sequences,json=stopSequences,proto3" json:"stop_sequences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplingParams) Reset() {
	*x = SamplingParams{}
	mi := &file_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplingParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplingParams) ProtoMessage() {}

func (x *SamplingParams) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplingParams.ProtoReflect.Descriptor instead.
func (*SamplingParams) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{4}
}

func (x *SamplingParams) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SamplingParams) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *SamplingParams) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *SamplingParams) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SamplingParams) GetStopSequences() []string {
	if x != nil {
		return x.StopSequences
	}
	return nil
}

// GenerateResponse — từng event Python gửi ngược lên Go.
type GenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type determines which field is populated.
	EventType GenerateEventType `protobuf:"varint,1,opt,name=event_type,json=eventType,proto3,enum=inference.GenerateEventType" json:"event_type,omitempty"`
	// Token event — một token text được sinh ra.
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// Tool use event — model muốn gọi một tool.
	ToolUse *ToolUse `protobuf:"bytes,3,opt,name=tool_use,json=toolUse,proto3" json:"tool_use,omitempty"`
	// Final event — gửi khi inference kết thúc.
	StopReason   StopReason `protobuf:"varint,4,opt,name=stop_reason,json=stopReason,proto3,enum=inference.StopReason" json:"stop_reason,omitempty"`
	FinishReason string     `protobuf:"bytes,5,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"` // "stop" | "length" | "tool_use" | "cancelled"
	// Thống kê (gửi kèm final event hoặc event riêng).
	Usage         *Usage `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateResponse) GetEventType() GenerateEventType {
	if x != nil {
		return x.EventType
	}
	return GenerateEventType_EVENT_UNSPECIFIED
}

func (x *GenerateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GenerateResponse) GetToolUse() *ToolUse {
	if x != nil {
		return x.ToolUse
	}
	return nil
}

func (x *GenerateResponse) GetStopReason() StopReason {
	if x != nil {
		return x.StopReason
	}
	return StopReason_STOP_UNSPECIFIED
}

func (x *GenerateResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *GenerateResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// ToolUse — model yêu cầu gọi tool.
type ToolUse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Arguments     string                 `protobuf:"bytes,3,opt,name=arguments,proto3" json:"arguments,omitempty"` // JSON string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolUse) Reset() {
	*x = ToolUse{}
	mi := &file_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolUse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolUse) ProtoMessage() {}

func (x *ToolUse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolUse.ProtoReflect.Descriptor instead.
func (*ToolUse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{6}
}

func (x *ToolUse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolUse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolUse) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

// Usage — token count statistics.
type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{7}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// BatchGenerateRequest — gửi batch requests xuống Python.
type BatchGenerateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batch ID để trace.
	BatchId string `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	// Các requests trong batch.
	Requests      []*GenerateRequest `protobuf:"bytes,2,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGenerateRequest) Reset() {
	*x = BatchGenerateRequest{}
	mi := &file_inference_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGenerateRequest) ProtoMessage() {}

func (x *BatchGenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGenerateRequest.ProtoReflect.Descriptor instead.
func (*BatchGenerateRequest) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{8}
}

func (x *BatchGenerateRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *BatchGenerateRequest) GetRequests() []*GenerateRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

// BatchGenerateResponse — stream event cho từng request trong batch.
// Mỗi response có request_id để Go scheduler route về đúng client.
type BatchGenerateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Request ID — để route event về đúng client channel.
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Event type.
	EventType GenerateEventType `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=inference.GenerateEventType" json:"event_type,omitempty"`
	// Token (cho EVENT_TOKEN).
	Token string `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	// Tool use (cho EVENT_TOOL_USE).
	ToolUse *ToolUse `protobuf:"bytes,4,opt,name=tool_use,json=toolUse,proto3" json:"tool_use,omitempty"`
	// Stop reason (cho EVENT_FINAL).
	StopReason   StopReason `protobuf:"varint,5,opt,name=stop_reason,json=stopReason,proto3,enum=inference.StopReason" json:"stop_reason,omitempty"`
	FinishReason string     `protobuf:"bytes,6,opt,name=finish_reason,json=finishReason,proto3" json:"finish_reason,omitempty"`
	// Usage stats (cho EVENT_FINAL).
	Usage         *Usage `protobuf:"bytes,7,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGenerateResponse) Reset() {
	*x = BatchGenerateResponse{}
	mi := &file_inference_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGenerateResponse) ProtoMessage() {}

func (x *BatchGenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inference_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGenerateResponse.ProtoReflect.Descriptor instead.
func (*BatchGenerateResponse) Descriptor() ([]byte, []int) {
	return file_inference_proto_rawDescGZIP(), []int{9}
}

func (x *BatchGenerateResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BatchGenerateResponse) GetEventType() GenerateEventType {
	if x != nil {
		return x.EventType
	}
	return GenerateEventType_EVENT_UNSPECIFIED
}

func (x *BatchGenerateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *BatchGenerateResponse) GetToolUse() *ToolUse {
	if x != nil {
		return x.ToolUse
	}
	return nil
}

func (x *BatchGenerateResponse) GetStopReason() StopReason {
	if x != nil {
		return x.StopReason
	}
	return StopReason_STOP_UNSPECIFIED
}

func (x *BatchGenerateResponse) GetFinishReason() string {
	if x != nil {
		return x.FinishReason
	}
	return ""
}

func (x *BatchGenerateResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

var File_inference_proto protoreflect.FileDescriptor

const file_inference_proto_rawDesc = "" +
	"\n" +
	"\x0finference.proto\x12\tinference\"\x99\x02\n" +
	"\x0fGenerateRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12.\n" +
	"\bmessages\x18\x03 \x03(\v2\x12.inference.MessageR\bmessages\x12#\n" +
	"\rsystem_prompt\x18\x04 \x01(\tR\fsystemPrompt\x12B\n" +
	"\x0fsampling_params\x18\x05 \x01(\v2\x19.inference.SamplingParamsR\x0esamplingParams\x12/\n" +
	"\x05tools\x18\x06 \x03(\v2\x19.inference.ToolDefinitionR\x05tools\"\xc9\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x122\n" +
	"\n" +
	"tool_calls\x18\x03 \x03(\v2\x13.inference.ToolCallR\ttoolCalls\x12 \n" +
	"\ftool_call_id\x18\x04 \x01(\tR\n" +
	"toolCallId\x12\x1f\n" +
	"\vtool_result\x18\x05 \x01(\tR\n" +
	"toolResult\x12\x19\n" +
	"\bis_error\x18\x06 \x01(\bR\aisError\"L\n" +
	"\bToolCall\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\"f\n" +
	"\x0eToolDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"parameters\x18\x03 \x01(\tR\n" +
	"parameters\"\xa2\x01\n" +
	"\x0eSamplingParams\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x01 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x02 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\x03 \x01(\x02R\x04topP\x12\x13\n" +
	"\x05top_k\x18\x04 \x01(\x05R\x04topK\x12%\n" +
	"\x0estop_sequences\x18\x05 \x03(\tR\rstopSequences\"\x99\x02\n" +
	"\x10GenerateResponse\x12;\n" +
	"\n" +
	"event_type\x18\x01 \x01(\x0e2\x1c.inference.GenerateEventTypeR\teventType\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12-\n" +
	"\btool_use\x18\x03 \x01(\v2\x12.inference.ToolUseR\atoolUse\x126\n" +
	"\vstop_reason\x18\x04 \x01(\x0e2\x15.inference.StopReasonR\n" +
	"stopReason\x12#\n" +
	"\rfinish_reason\x18\x05 \x01(\tR\ffinishReason\x12&\n" +
	"\x05usage\x18\x06 \x01(\v2\x10.inference.UsageR\x05usage\"K\n" +
	"\aToolUse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\targuments\x18\x03 \x01(\tR\targuments\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"i\n" +
	"\x14BatchGenerateRequest\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x126\n" +
	"\brequests\x18\x02 \x03(\v2\x1a.inference.GenerateRequestR\brequests\"\xbd\x02\n" +
	"\x15BatchGenerateResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12;\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2\x1c.inference.GenerateEventTypeR\teventType\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12-\n" +
	"\btool_use\x18\x04 \x01(\v2\x12.inference.ToolUseR\atoolUse\x126\n" +
	"\vstop_reason\x18\x05 \x01(\x0e2\x15.inference.StopReasonR\n" +
	"stopReason\x12#\n" +
	"\rfinish_reason\x18\x06 \x01(\tR\ffinishReason\x12&\n" +
	"\x05usage\x18\a \x01(\v2\x10.inference.UsageR\x05usage*`\n" +
	"\x11GenerateEventType\x12\x15\n" +
	"\x11EVENT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vEVENT_TOKEN\x10\x01\x12\x12\n" +
	"\x0eEVENT_TOOL_USE\x10\x02\x12\x0f\n" +
	"\vEVENT_FINAL\x10\x03*\x81\x01\n" +
	"\n" +
	"StopReason\x12\x14\n" +
	"\x10STOP_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTOP_END_TURN\x10\x01\x12\x13\n" +
	"\x0fSTOP_MAX_TOKENS\x10\x02\x12\x11\n" +
	"\rSTOP_TOOL_USE\x10\x03\x12\x12\n" +
	"\x0eSTOP_CANCELLED\x10\x04\x12\x0e\n" +
	"\n" +
	"STOP_ERROR\x10\x052Y\n" +
	"\x10InferenceService\x12E\n" +
	"\bGenerate\x12\x1a.inference.GenerateRequest\x1a\x1b.inference.GenerateResponse0\x012m\n" +
	"\x15BatchInferenceService\x12T\n" +
	"\rBatchGenerate\x12\x1f.inference.BatchGenerateRequest\x1a .inference.BatchGenerateResponse0\x01B!Z\x1fgo-server/internal/inference/pbb\x06proto3"

var (
	file_inference_proto_rawDescOnce sync.Once
	file_inference_proto_rawDescData []byte
)

func file_inference_proto_rawDescGZIP() []byte {
	file_inference_proto_rawDescOnce.Do(func() {
		file_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)))
	})
	return file_inference_proto_rawDescData
}

var file_inference_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_inference_proto_goTypes = []any{
	(GenerateEventType)(0),        // 0: inference.GenerateEventType
	(StopReason)(0),               // 1: inference.StopReason
	(*GenerateRequest)(nil),       // 2: inference.GenerateRequest
	(*Message)(nil),               // 3: inference.Message
	(*ToolCall)(nil),              // 4: inference.ToolCall
	(*ToolDefinition)(nil),        // 5: inference.ToolDefinition
	(*SamplingParams)(nil),        // 6: inference.SamplingParams
	(*GenerateResponse)(nil),      // 7: inference.GenerateResponse
	(*ToolUse)(nil),               // 8: inference.ToolUse
	(*Usage)(nil),                 // 9: inference.Usage
	(*BatchGenerateRequest)(nil),  // 10: inference.BatchGenerateRequest
	(*BatchGenerateResponse)(nil), // 11: inference.BatchGenerateResponse
}
var file_inference_proto_depIdxs = []int32{
	3,  // 0: inference.GenerateRequest.messages:type_name -> inference.Message
	6,  // 1: inference.GenerateRequest.sampling_params:type_name -> inference.SamplingParams
	5,  // 2: inference.GenerateRequest.tools:type_name -> inference.ToolDefinition
	4,  // 3: inference.Message.tool_calls:type_name -> inference.ToolCall
	0,  // 4: inference.GenerateResponse.event_type:type_name -> inference.GenerateEventType
	8,  // 5: inference.GenerateResponse.tool_use:type_name -> inference.ToolUse
	1,  // 6: inference.GenerateResponse.stop_reason:type_name -> inference.StopReason
	9,  // 7: inference.GenerateResponse.usage:type_name -> inference.Usage
	2,  // 8: inference.BatchGenerateRequest.requests:type_name -> inference.GenerateRequest
	0,  // 9: inference.BatchGenerateResponse.event_type:type_name -> inference.GenerateEventType
	8,  // 10: inference.BatchGenerateResponse.tool_use:type_name -> inference.ToolUse
	1,  // 11: inference.BatchGenerateResponse.stop_reason:type_name -> inference.StopReason
	9,  // 12: inference.BatchGenerateResponse.usage:type_name -> inference.Usage
	2,  // 13: inference.InferenceService.Generate:input_type -> inference.GenerateRequest
	10, // 14: inference.BatchInferenceService.BatchGenerate:input_type -> inference.BatchGenerateRequest
	7,  // 15: inference.InferenceService.Generate:output_type -> inference.GenerateResponse
	11, // 16: inference.BatchInferenceService.BatchGenerate:output_type -> inference.BatchGenerateResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_inference_proto_init() }
func file_inference_proto_init() {
	if File_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inference_proto_rawDesc), len(file_inference_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_inference_proto_goTypes,
		DependencyIndexes: file_inference_proto_depIdxs,
		EnumInfos:         file_inference_proto_enumTypes,
		MessageInfos:      file_inference_proto_msgTypes,
	}.Build()
	File_inference_proto = out.File
	file_inference_proto_goTypes = nil
	file_inference_proto_depIdxs = nil
}
