// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: inference.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceService_Generate_FullMethodName = "/inference.InferenceService/Generate"
)

// InferenceServiceClient is the client API for InferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// InferenceService — Python worker exposes this.
// Go server calls Generate() to start inference, receives a stream of tokens.
type InferenceServiceClient interface {
	// Generate tokens from messages. Server-streaming: Python gửi từng token về Go.
	Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error)
}

type inferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceServiceClient(cc grpc.ClientConnInterface) InferenceServiceClient {
	return &inferenceServiceClient{cc}
}

func (c *inferenceServiceClient) Generate(ctx context.Context, in *GenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GenerateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InferenceService_ServiceDesc.Streams[0], InferenceService_Generate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateRequest, GenerateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceService_GenerateClient = grpc.ServerStreamingClient[GenerateResponse]

// InferenceServiceServer is the server API for InferenceService service.
// All implementations must embed UnimplementedInferenceServiceServer
// for forward compatibility.
//
// InferenceService — Python worker exposes this.
// Go server calls Generate() to start inference, receives a stream of tokens.
type InferenceServiceServer interface {
	// Generate tokens from messages. Server-streaming: Python gửi từng token về Go.
	Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error
	mustEmbedUnimplementedInferenceServiceServer()
}

// UnimplementedInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceServiceServer struct{}

func (UnimplementedInferenceServiceServer) Generate(*GenerateRequest, grpc.ServerStreamingServer[GenerateResponse]) error {
	return status.Error(codes.Unimplemented, "method Generate not implemented")
}
func (UnimplementedInferenceServiceServer) mustEmbedUnimplementedInferenceServiceServer() {}
func (UnimplementedInferenceServiceServer) testEmbeddedByValue()                          {}

// UnsafeInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceServiceServer will
// result in compilation errors.
type UnsafeInferenceServiceServer interface {
	mustEmbedUnimplementedInferenceServiceServer()
}

func RegisterInferenceServiceServer(s grpc.ServiceRegistrar, srv InferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceService_ServiceDesc, srv)
}

func _InferenceService_Generate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InferenceServiceServer).Generate(m, &grpc.GenericServerStream[GenerateRequest, GenerateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InferenceService_GenerateServer = grpc.ServerStreamingServer[GenerateResponse]

// InferenceService_ServiceDesc is the grpc.ServiceDesc for InferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.InferenceService",
	HandlerType: (*InferenceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Generate",
			Handler:       _InferenceService_Generate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inference.proto",
}

const (
	BatchInferenceService_BatchGenerate_FullMethodName = "/inference.BatchInferenceService/BatchGenerate"
)

// BatchInferenceServiceClient is the client API for BatchInferenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BatchInferenceService — Go server gửi batch requests, Python xử lý và stream
// kết quả về cho từng request qua request_id.
type BatchInferenceServiceClient interface {
	// BatchGenerate nhận nhiều requests trong một lần, chạy model.generate()
	// với batched inputs (padding + attention mask), stream kết quả về.
	BatchGenerate(ctx context.Context, in *BatchGenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BatchGenerateResponse], error)
}

type batchInferenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBatchInferenceServiceClient(cc grpc.ClientConnInterface) BatchInferenceServiceClient {
	return &batchInferenceServiceClient{cc}
}

func (c *batchInferenceServiceClient) BatchGenerate(ctx context.Context, in *BatchGenerateRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BatchGenerateResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BatchInferenceService_ServiceDesc.Streams[0], BatchInferenceService_BatchGenerate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchGenerateRequest, BatchGenerateResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BatchInferenceService_BatchGenerateClient = grpc.ServerStreamingClient[BatchGenerateResponse]

// BatchInferenceServiceServer is the server API for BatchInferenceService service.
// All implementations must embed UnimplementedBatchInferenceServiceServer
// for forward compatibility.
//
// BatchInferenceService — Go server gửi batch requests, Python xử lý và stream
// kết quả về cho từng request qua request_id.
type BatchInferenceServiceServer interface {
	// BatchGenerate nhận nhiều requests trong một lần, chạy model.generate()
	// với batched inputs (padding + attention mask), stream kết quả về.
	BatchGenerate(*BatchGenerateRequest, grpc.ServerStreamingServer[BatchGenerateResponse]) error
	mustEmbedUnimplementedBatchInferenceServiceServer()
}

// UnimplementedBatchInferenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBatchInferenceServiceServer struct{}

func (UnimplementedBatchInferenceServiceServer) BatchGenerate(*BatchGenerateRequest, grpc.ServerStreamingServer[BatchGenerateResponse]) error {
	return status.Error(codes.Unimplemented, "method BatchGenerate not implemented")
}
func (UnimplementedBatchInferenceServiceServer) mustEmbedUnimplementedBatchInferenceServiceServer() {}
func (UnimplementedBatchInferenceServiceServer) testEmbeddedByValue()                               {}

// UnsafeBatchInferenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BatchInferenceServiceServer will
// result in compilation errors.
type UnsafeBatchInferenceServiceServer interface {
	mustEmbedUnimplementedBatchInferenceServiceServer()
}

func RegisterBatchInferenceServiceServer(s grpc.ServiceRegistrar, srv BatchInferenceServiceServer) {
	// If the following call panics, it indicates UnimplementedBatchInferenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BatchInferenceService_ServiceDesc, srv)
}

func _BatchInferenceService_BatchGenerate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BatchGenerateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BatchInferenceServiceServer).BatchGenerate(m, &grpc.GenericServerStream[BatchGenerateRequest, BatchGenerateResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BatchInferenceService_BatchGenerateServer = grpc.ServerStreamingServer[BatchGenerateResponse]

// BatchInferenceService_ServiceDesc is the grpc.ServiceDesc for BatchInferenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BatchInferenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "inference.BatchInferenceService",
	HandlerType: (*BatchInferenceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchGenerate",
			Handler:       _BatchInferenceService_BatchGenerate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "inference.proto",
}
