# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from worker.pb import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub(object):
    """InferenceService — Python worker exposes this.
    Go server calls Generate() to start inference, receives a stream of tokens.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Generate = channel.unary_stream(
                '/inference.InferenceService/Generate',
                request_serializer=inference__pb2.GenerateRequest.SerializeToString,
                response_deserializer=inference__pb2.GenerateResponse.FromString,
                _registered_method=True)


class InferenceServiceServicer(object):
    """InferenceService — Python worker exposes this.
    Go server calls Generate() to start inference, receives a stream of tokens.
    """

    def Generate(self, request, context):
        """Generate tokens from messages. Server-streaming: Python gửi từng token về Go.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=inference__pb2.GenerateRequest.FromString,
                    response_serializer=inference__pb2.GenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """InferenceService — Python worker exposes this.
    Go server calls Generate() to start inference, receives a stream of tokens.
    """

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inference.InferenceService/Generate',
            inference__pb2.GenerateRequest.SerializeToString,
            inference__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BatchInferenceServiceStub(object):
    """============================================================================
    Batch Inference — Continuous Batching support
    ============================================================================

    BatchInferenceService — Go server gửi batch requests, Python xử lý và stream
    kết quả về cho từng request qua request_id.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchGenerate = channel.unary_stream(
                '/inference.BatchInferenceService/BatchGenerate',
                request_serializer=inference__pb2.BatchGenerateRequest.SerializeToString,
                response_deserializer=inference__pb2.BatchGenerateResponse.FromString,
                _registered_method=True)


class BatchInferenceServiceServicer(object):
    """============================================================================
    Batch Inference — Continuous Batching support
    ============================================================================

    BatchInferenceService — Go server gửi batch requests, Python xử lý và stream
    kết quả về cho từng request qua request_id.
    """

    def BatchGenerate(self, request, context):
        """BatchGenerate nhận nhiều requests trong một lần, chạy model.generate()
        với batched inputs (padding + attention mask), stream kết quả về.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BatchInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchGenerate': grpc.unary_stream_rpc_method_handler(
                    servicer.BatchGenerate,
                    request_deserializer=inference__pb2.BatchGenerateRequest.FromString,
                    response_serializer=inference__pb2.BatchGenerateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inference.BatchInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inference.BatchInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BatchInferenceService(object):
    """============================================================================
    Batch Inference — Continuous Batching support
    ============================================================================

    BatchInferenceService — Go server gửi batch requests, Python xử lý và stream
    kết quả về cho từng request qua request_id.
    """

    @staticmethod
    def BatchGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/inference.BatchInferenceService/BatchGenerate',
            inference__pb2.BatchGenerateRequest.SerializeToString,
            inference__pb2.BatchGenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
